//! Reusable synthesis primitives backed by one shared harmonic tablebank.

use crate::dsp::RenderError;
use std::sync::OnceLock;

const TABLE_LEN: usize = 2_048;
const HARMONIC_LIMITS: [usize; 11] = [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1_024];
static TABLE_BANKS: OnceLock<TableBanks> = OnceLock::new();

/// Harmonic waveform generated by [`Oscillator`].
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Waveform {
    Sine,
    Saw,
    Square,
    Triangle,
}

/// A per-voice linear attack-decay-sustain-release envelope.
#[derive(Clone, Debug)]
pub struct Adsr {
    on_frame: u64,
    attack_seconds: f64,
    decay_seconds: f64,
    sustain: f64,
    release: Option<Release>,
}

#[derive(Clone, Debug)]
struct Release {
    frame: u64,
    seconds: f64,
    amplitude: f64,
}

impl Adsr {
    /// Capture note-on time and the attack, decay, and sustain parameters.
    pub fn new(
        on_frame: u64,
        attack_seconds: f64,
        decay_seconds: f64,
        sustain: f64,
    ) -> Result<Self, RenderError> {
        validate_duration("attack", attack_seconds)?;
        validate_duration("decay", decay_seconds)?;
        if !sustain.is_finite() || !(0.0..=1.0).contains(&sustain) {
            return Err(RenderError::Nonfinite(format!(
                "ADSR sustain {sustain} must be finite and within 0..=1"
            )));
        }
        Ok(Self {
            on_frame,
            attack_seconds,
            decay_seconds,
            sustain,
            release: None,
        })
    }

    /// Capture the envelope level and release duration at note-off.
    pub fn release(
        &mut self,
        frame: u64,
        rate: f64,
        release_seconds: f64,
    ) -> Result<(), RenderError> {
        validate_rate(rate)?;
        validate_duration("release", release_seconds)?;
        let amplitude = self.value(frame, rate)?;
        self.release = Some(Release {
            frame,
            seconds: release_seconds,
            amplitude,
        });
        Ok(())
    }

    /// Evaluate the envelope at a sample instant.
    pub fn value(&self, frame: u64, rate: f64) -> Result<f64, RenderError> {
        validate_rate(rate)?;
        if frame < self.on_frame {
            return Ok(0.0);
        }

        if let Some(release) = &self.release {
            if frame >= release.frame {
                if release.seconds == 0.0 {
                    return Ok(0.0);
                }
                let elapsed_frames = (frame - release.frame) as f64;
                let release_frames = release.seconds * rate;
                return Ok(release.amplitude * (1.0 - elapsed_frames / release_frames).max(0.0));
            }
        }

        let elapsed_frames = (frame - self.on_frame) as f64;
        let attack_frames = self.attack_seconds * rate;
        if attack_frames > 0.0 && elapsed_frames < attack_frames {
            return Ok(elapsed_frames / attack_frames);
        }
        let decay_elapsed_frames = elapsed_frames - attack_frames;
        let decay_frames = self.decay_seconds * rate;
        if decay_frames > 0.0 && decay_elapsed_frames < decay_frames {
            return Ok(1.0 + (self.sustain - 1.0) * decay_elapsed_frames / decay_frames);
        }
        Ok(self.sustain)
    }

    /// Whether a released envelope has reached zero.
    pub fn finished(&self, frame: u64, rate: f64) -> Result<bool, RenderError> {
        validate_rate(rate)?;
        let Some(release) = &self.release else {
            return Ok(false);
        };
        if frame < release.frame {
            return Ok(false);
        }
        if release.amplitude == 0.0 || release.seconds == 0.0 {
            return Ok(true);
        }
        Ok((frame - release.frame) as f64 >= release.seconds * rate)
    }
}

/// A phase accumulator measured in cycles.
#[derive(Clone, Debug)]
pub struct Oscillator {
    waveform: Waveform,
    phase: f64,
}

impl Oscillator {
    /// Create an oscillator at a phase in the inclusive range `0.0..=1.0`.
    /// A phase of one cycle is canonicalized to zero.
    pub fn new(waveform: Waveform, phase_cycles: f64) -> Result<Self, RenderError> {
        validate_phase(phase_cycles)?;
        Ok(Self {
            waveform,
            phase: canonical_phase(phase_cycles),
        })
    }

    /// Reset the phase. A phase of one cycle wraps to zero.
    pub fn reset(&mut self, phase_cycles: f64) -> Result<(), RenderError> {
        validate_phase(phase_cycles)?;
        self.phase = canonical_phase(phase_cycles);
        Ok(())
    }

    /// Sample the current phase, then advance it by `frequency_hz / rate`.
    pub fn sample(&mut self, frequency_hz: f64, rate: f64) -> Result<f64, RenderError> {
        validate_rate(rate)?;
        if !frequency_hz.is_finite() {
            return Err(RenderError::Nonfinite(
                "oscillator frequency must be finite".into(),
            ));
        }
        if frequency_hz.abs() > rate * 0.5 {
            return Err(RenderError::Nonfinite(format!(
                "oscillator frequency {frequency_hz} is outside the Nyquist range"
            )));
        }

        let bank_index = select_bank(frequency_hz.abs(), rate);
        let sample = table_sample(
            TABLE_BANKS
                .get_or_init(TableBanks::build)
                .waveform(self.waveform, bank_index),
            self.phase,
        );
        self.phase = (self.phase + frequency_hz / rate).rem_euclid(1.0);
        Ok(sample)
    }
}

fn validate_phase(phase_cycles: f64) -> Result<(), RenderError> {
    if !phase_cycles.is_finite() || !(0.0..=1.0).contains(&phase_cycles) {
        return Err(RenderError::Nonfinite(format!(
            "oscillator phase {phase_cycles} must be finite and within 0..=1"
        )));
    }
    Ok(())
}

fn validate_rate(rate: f64) -> Result<(), RenderError> {
    if !rate.is_finite() || rate <= 0.0 {
        return Err(RenderError::Nonfinite(format!(
            "sample rate {rate} must be finite and positive"
        )));
    }
    Ok(())
}

fn validate_duration(name: &str, seconds: f64) -> Result<(), RenderError> {
    if !seconds.is_finite() || !(0.0..=1_800.0).contains(&seconds) {
        return Err(RenderError::Nonfinite(format!(
            "ADSR {name} duration {seconds} must be finite and within 0..=1800 seconds"
        )));
    }
    Ok(())
}

fn canonical_phase(phase_cycles: f64) -> f64 {
    if phase_cycles == 1.0 {
        0.0
    } else {
        phase_cycles
    }
}

fn select_bank(frequency_hz: f64, rate: f64) -> usize {
    if frequency_hz == 0.0 {
        return HARMONIC_LIMITS.len() - 1;
    }
    let nyquist = rate * 0.5;
    HARMONIC_LIMITS
        .iter()
        .rposition(|limit| *limit as f64 * frequency_hz <= nyquist)
        // A valid frequency can only reach this fallback through floating
        // point edge behavior. Retaining the fundamental is deterministic.
        .unwrap_or(0)
}

fn table_sample(table: &[f64], phase: f64) -> f64 {
    let position = phase * TABLE_LEN as f64;
    let left = position.floor() as usize;
    let fraction = position - left as f64;
    let right = (left + 1) % TABLE_LEN;
    table[left] + (table[right] - table[left]) * fraction
}

struct TableBanks {
    sine: Vec<Vec<f64>>,
    saw: Vec<Vec<f64>>,
    square: Vec<Vec<f64>>,
    triangle: Vec<Vec<f64>>,
}

impl TableBanks {
    fn build() -> Self {
        let mut sine = vec![0.0; TABLE_LEN];
        let mut saw = vec![0.0; TABLE_LEN];
        let mut square = vec![0.0; TABLE_LEN];
        let mut triangle = vec![0.0; TABLE_LEN];
        let mut banks = Self {
            sine: Vec::with_capacity(HARMONIC_LIMITS.len()),
            saw: Vec::with_capacity(HARMONIC_LIMITS.len()),
            square: Vec::with_capacity(HARMONIC_LIMITS.len()),
            triangle: Vec::with_capacity(HARMONIC_LIMITS.len()),
        };

        for harmonic in 1..=HARMONIC_LIMITS[HARMONIC_LIMITS.len() - 1] {
            let harmonic_f64 = harmonic as f64;
            let odd = harmonic % 2 == 1;
            let triangle_sign = if ((harmonic - 1) / 2) % 2 == 0 {
                1.0
            } else {
                -1.0
            };
            let saw_coefficient = -2.0 / (std::f64::consts::PI * harmonic_f64);
            let square_coefficient = 4.0 / (std::f64::consts::PI * harmonic_f64);
            let triangle_coefficient =
                8.0 * triangle_sign / (std::f64::consts::PI.powi(2) * harmonic_f64.powi(2));

            for sample_index in 0..TABLE_LEN {
                let phase = sample_index as f64 / TABLE_LEN as f64;
                let harmonic_sine = (std::f64::consts::TAU * phase * harmonic_f64).sin();
                if harmonic == 1 {
                    sine[sample_index] = harmonic_sine;
                }
                saw[sample_index] += saw_coefficient * harmonic_sine;
                if odd {
                    square[sample_index] += square_coefficient * harmonic_sine;
                    triangle[sample_index] += triangle_coefficient * harmonic_sine;
                }
            }

            if harmonic.is_power_of_two() {
                banks.sine.push(sine.clone());
                banks.saw.push(saw.clone());
                banks.square.push(square.clone());
                banks.triangle.push(triangle.clone());
            }
        }
        banks
    }

    fn waveform(&self, waveform: Waveform, bank_index: usize) -> &[f64] {
        match waveform {
            Waveform::Sine => &self.sine[bank_index],
            Waveform::Saw => &self.saw[bank_index],
            Waveform::Square => &self.square[bank_index],
            Waveform::Triangle => &self.triangle[bank_index],
        }
    }
}
